### ISSUE TITLE
Tex equations support?

### ISSUE THREAD

**Issue by jakeoung** [Lio5n/blue-star#1]
Thanks for the amazing plugin! Currently, it doesn't support equations by $ $ or $$ $$. Any plan to support?

**Comment by Lio5n** [comment]
Hi, this plugin only fills the fields of Anki cards with content from Obsidian. The display issue with TeX equations might need to be resolved with an Anki plugin. @jakeoung

**Comment by jakeoung** [comment]
Oops, okay. I didn't have any issue from other plugins, but thanks for the reply!

**Comment by jakeoung** [comment]
I managed to work, changing the note type from Basic to KaTeX and Markdown Basic, using a plugin.
