### ISSUE TITLE
你好，请问blue star支持字段映射到anki吗

### ISSUE THREAD

**Issue by xiaoliaichimalatang** [Lio5n/blue-star#2]
感谢作者开发这款插件！
我之前有用过ob 2 anki插件，它不支持多字段的映射,使用了一段时间后，我给自己的英语学习模板增加了几个字段，之后用ob2anki同步的时候导入到anki的卡片都错乱掉了……所以我开始寻找其他可以to anki的插件。读blue star的read me文档，看到有多字段的字样，无奈没有相关知识储备，理解得磕磕绊绊的，查询了ob的社区，b站还有油管都没有找到有人讨论。所以想问问作者，blue star的多字段支持映射到anki笔记模板的字段吗。
比如一张英语表达的笔记模板，有词汇、来源摘录、笔记、相关词汇这几个字段，我可以在ob里整理笔记，然后用blue star映射过去吗。
以及，作者考虑开一个discussion区吗，有讨论区的话，类似这条不重要的内容都可以发到那里，用户之间自行讨论，发到issue里有点干扰作者（抱歉抱歉）。

**Comment by Lio5n** [comment]
你好，

支持的，根据你的文档内容格式，选择合适的匹配模式（`Match Mode`设置里的名称），可以分割出多个字段。每个字段按顺序对应 Anki 里的字段，如果分割出的字段少于 Anki 里的字段，有几个就填充几个，如果分割出的字段多于 Anki 里的字段，Anki 里有的字段还是会正常填充，多余的会丢弃。

## 给你举个例子

### 文档

假如我的文档内容如下：

````markdown
```anki
deck: Test
model: MyBasic (Left)
match: single-delimiter
field: ::
html: true
ignore: false
```

词汇 1
::
来源摘录
::
笔记
::
相关词汇

词汇 2
::
来源摘录
::
笔记
::
相关词汇
````

其中我设置了按`::`符号分割每个字段（我喜欢在文档中配置生成规则，这样不用去改 obsidian 中的设置，就可以单独控制每个文档生成 Anki 卡片的行为）。

### Anki Note Type

我的 Anki Note Type 如下：

<img width="700" alt="Screenshot 2024-11-17 at 01 22 16" src="https://github.com/user-attachments/assets/e4e7dd3d-a2a3-48b4-bfaf-7c470a419922">

### 生成的卡片如下

<img width="1760" alt="Screenshot 2024-11-17 at 01 26 31" src="https://github.com/user-attachments/assets/04de7d18-6f57-436f-8625-3be615845470">

## 匹配模式

给你介绍一下内置的匹配模式，以免 README 中有写的不清楚的地方。

- section-subsection：第一个字段（标题+紧跟的内容到下一级标题为止），第二个及以后的个字段（以标题的下一级标题分割出来的多个字段）
- heading-paragraph：第一个字段（标题），第二个字段（标题下的内容）
- multi-subsection：多个字段（以标题的下一级标题分割出来的多个字段）
- multi-subparagrap：多个字段（以标题的下一级标题分割出来的多个字段，但是不包括标题本身）
- custom-delimiter：多个字段（根据你自定义的分割符分割出的多个字段，分割符包括卡片开始标识、卡片字段分割标识、卡片结束标识）
- single-delimiter：多个字段（根据单个分割符分割的多个字段，每个空行开始一个新的卡片）
- regex：根据正则表达式分割字段，插件自身提供了一些正则表达式，它们大多都来自 obsidian_2_anki，当然你也可以写自己的正则表达式。我觉得 obsidian_2_anki 应该也支持多个字段，只要正则表达式能分割出来多个字段。如果你喜欢 obsidian_2_anki 的自动同步或者生成卡片后自动生成标记等功能的话，你可以尝试写适合你想要的分割模式的正则表达式解决。怎么写正则表达式我就帮不了你了，我就是因为实在写不出来我想要的正则表达式，才自己开发了这个插件😂。

## 其他

这个插件刚上线，如果以后用的人多了，再开 discussion 区吧。

有什么问题，你在这里问就好，没关系的。

希望以上回答可以解决你的问题。

@xiaoliaichimalatang

**Comment by xiaoliaichimalatang** [comment]
十分十分十分感谢作者的回复！
