### ISSUE TITLE
使用过程中我的一些问题

### ISSUE THREAD

**Issue by xiaoliaichimalatang** [Lio5n/blue-star#5]
你好。已用您之前您回复的single delimiter匹配方式成功创建了我自己的卡片（十分感谢！）。在使用过程中我有以下这几个问题：
1. “anki model: 笔记模板” 是否不识别用中文命名的笔记模板。
   我填写了中文笔记模板后点⭐，显示该model不存在，把笔记模板改填为Basic后再点⭐则成功创建了卡片。
2. blue star更新卡片的逻辑是否是以卡片首字段为依据，判定第一个字段相同的卡片为同一张卡片。
   我在ob中修改笔记，对第一个字段的内容做出了改动，点⭐同步后，在anki库里发现这张卡片没有被更新，库里新增了一张首字段不同其余字段的内容都相同的卡片。
   我之前使用ob2anki，在同步给anki的时候会在ob里每条笔记底下生成一条id信息，在ob里修改首字段内容也能把这个改动同步过去。请问作者将来有计划支持这种更新笔记的方式吗。
3. 作者将来有计划支持ob内单条笔记内的标签也同步进anki的对应卡片里面吗（区别于文件开头定义的anki tag）
   效果：我在ob当前文件里记笔记，单独给部分笔记添加 #某主题 的标签，当前笔记文件被同步进anki后，这几条带有 #某主题 标签的笔记在anki里也会带上对应的标签。
   ob2anki有这个功能，可惜原插件该功能目前尚不支持中文标签。一个up主修改了js文件，使得中文标签可被导入。这是文件地址和up主发的视频：
   https://github.com/Carrie-L/Obsidian_to_anki_update
   https://www.bilibili.com/video/BV1WYsQezEsq/?share_source=copy_web&vd_source=a4695331604c45743368a5e0d13da6ac
   
   
   再次感谢作者发布这么便捷的插件！！

**Comment by Lio5n** [comment]
你好：

感谢你的使用和反馈。

**1.**
我测试了一下，支持中文的，如下图
<img width="799" alt="Screenshot 2024-11-20 at 09 02 11" src="https://github.com/user-attachments/assets/1720923f-242b-4217-968f-68a9c8bcb040">

**2. & 3.**
是的，是以第一个字段是否相同判定是否为同一张卡片。

记录卡片 ID 和根据文档 tag 生成 anki 卡片 tag，这两个功能目前应该不会支持。第一因为时间精力有限，第二因为我这个插件并不想替代 ob2anki，只是想作为它的一个补充，或者另一种使用方式。

**Comment by Lio5n** [comment]
@xiaoliaichimalatang 上一条忘了@，请看上一条

**Comment by xiaoliaichimalatang** [comment]
明白啦，感谢作者回复。
